### ISSUE TITLE
Task 02 main.cc does nothing

### ISSUE THREAD

**Issue by jesusgn90** [jorgemgn/curso-cplus-cplus#1]
Hi team,

Looking at the tasks, I've noticed that `src/task-02/main.cc` has nothing to do, just a `return 0;`.

We need to add the logic for that task.

Regards,
Jesús

**Comment by jorgemgn** [comment]
Hi,

Fixed the error.

https://github.com/jorgemgn/curso-cplus-cplus/pull/2

Regards,
Jorge

**Comment by jesusgn90** [comment]
The file still does nothing, just a simple `return` statement, https://github.com/jorgemgn/curso-cplus-cplus/blob/master/src/task-02/main.cc, please add the proper code according to task number 2.

**Comment by jorgemgn** [comment]
Hello again,

In the following [PR](https://github.com/jorgemgn/curso-cplus-cplus/pull/3) I leave my contribution to the resolution of the issue.

Greetings
Jorge

**Comment by jesusgn90** [comment]
Still wrong due to https://github.com/jorgemgn/curso-cplus-cplus/pull/3#issuecomment-526834813

**Comment by jorgemgn** [comment]
He escrito un código nuevo. Compilado y funciona.
